name: Build and push to ecr

on:
  push:
    branches: [main, staging]

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    uses: b-zago/actions/.github/workflows/build-push-ecr-lambda.yaml@v1
    secrets: inherit
